### ISSUE TITLE
Reflect whether an asset is editable

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-backend#11]
Ultimately assets will only be editable by people whose department/institution matches that of the asset. The backend should provide feedback per asset on whether the authenticated user can edit the asset and enforce that permission.

See https://github.com/uisautomation/iar-frontend/issues/20.

**Comment by rjw57** [comment]
@abrahammartin notes that currently the department field is not required and so implementing this permission model would be difficult.

**Comment by rjw57** [comment]
Blocked on having a more specific spec for this permission from UX.

**Comment by abrahammartin** [comment]
This is part of the API validations task #10 , that should or should not allow a user to edit/delete an asset depending if they are from the same department.
