### ISSUE TITLE
HTTP DELETE should make is_deleted = True but not delete an asset

### ISSUE THREAD

**Issue by rjw57** [uisautomation/iar-backend#13]
Currently, DELETE-ing an asset is not undo-able without restoring from backup. We should consider adding an "is_deleted" column to guard against accidental deletion.

 - Create deleted_at that fills in when you try to delete the asset. Is a datetime field.
 - Modify the ModelView delete function to not delete the asset but instead to fill in the deleted_at field.
 - Modify the list method from the ModelView to not list the assets that have deleted_at not null

**Comment by abrahammartin** [comment]
I think so

**Comment by rjw57** [comment]
OK.

**Comment by abrahammartin** [comment]
not deleting the asset but change deleted_at
